#
# Zsh config. A lot of this came from https://scriptingosx.com/2019/06/moving-to-zsh/
#

# This makes wildcards in the shell case-insensitive.
# i.e. %> ls ~/m*
# setopt NO_CASE_GLOB

# Where should the zsh history file be stored?
# How many commands should be stored in the session?
# How many commands should be stored in the history file?
HISTFILE=${ZDOTDIR:-$HOME}/.zsh_history
SAVEHIST=5000
HISTSIZE=2000

# Share history across multiple zsh sessions and
# append to the history file instead of overwriting it.
setopt SHARE_HISTORY
setopt APPEND_HISTORY

# Correct mistyped commands (we'll see if it is annoying):
# n: execute as typed
# y: accept and execute the suggested correction
# a: abort and do nothing
# e: return to the prompt to continue editing
setopt CORRECT
setopt CORRECT_ALL

#
# This craziness integrates git with zsh, which we'll use in the prompt.
#

# Load version control info
autoload -Uz vcs_info
precmd() { vcs_info }

# Format the vcs_info_msg_0_ variable
zstyle ':vcs_info:git:*' check-for-changes true
#zstyle ':vcs_info:git:*' unstagedstr '!'
#zstyle ':vcs_info:git:*' stagedstr '+'
#zstyle ':vcs_info:git:*' formats '(%u%c %b)'
zstyle ':vcs_info:git:*' formats '(%b)'

# Need this for the substitution to work
setopt PROMPT_SUBST

#
# Shell prompt
#
PROMPT=$'\n''[%D{%a %b %d}, %*] %F{green}%~%f'$'\n''%n %F{yellow}${vcs_info_msg_0_}%f# '

#
# Aliases. The -g meams the alias will work *anywhere* in a command.
#
alias -g ls='ls -GF'
alias -g ll='ls -l'
alias -g la='ls -la'
alias grep='grep -n'
alias log='git log'
alias h='history'
alias hi='history | grep'
alias zip='zip -x "*.DS_Store" -x "*.svn" -x "*.swp"'

# Git alias for working with dotfile repo from github
alias dot='/usr/local/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME'

# Mac stuff
alias mvim='/Applications/MacVim.app/Contents/MacOS/Vim -g'
alias g='mvim'
alias mdiff='mvim -d'
alias show_dot_files='defaults write com.apple.finder AppleShowAllFiles TRUE' 
alias hide_dot_files='defaults write com.apple.finder AppleShowAllFiles FALSE'

# Clean up Javascript tags generated by ctags.
# See https://medium.com/adorableio/modern-javascript-ctags-configuration-199884dbcc1
alias jstags='ctags -R -f .tags && sed -i "" -E "/^\(if|switch|function|module\.exports|it|describe\).+language:js$/d" .tags'

#
# Functions
#
function mc() { 
    mkdir -p "$1" && cd "$1";
}
function fjs() {
    find $1 -name "*.js" -or -name "*.vue";
}

#
# Zsh completions
#
autoload -Uz compinit && compinit

